services:
  bot:
    build: .
    container_name: technobot
    volumes:
      type: bind
      source: ./database.db
      target: /app/
    environment:
      - DISCORD_BOT_TOKEN=

# docker run --name technobot --mount type=bind,source="$(pwd)"/data/database.db,target=/app/database.db [IMAGE-NAME]